### ISSUE TITLE
PKGBUILD now exists on Arch Linux User Repository

### ISSUE THREAD

**Issue by AdamSLevy** [nathanielc/vim-tickscript#6]
Arch Linux users can now install this syntax highlighting from the AUR without using a plugin manager. The PKGBUILD can be found here: [https://aur.archlinux.org/packages/vim-tickscript-git/](https://aur.archlinux.org/packages/vim-tickscript-git/) or cloned from here: [https://aur.archlinux.org/vim-tickscript-git.git ](https://aur.archlinux.org/vim-tickscript-git.git)

**Comment by nathanielc** [comment]
Thanks! As an arch user myself, this is nice!
